# Generated by Django 5.2.17 on 2026-09-09 14:22

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Exercise',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=150, unique=True, verbose_name='نام حرکت')),
                ('slug', models.SlugField(max_length=150, unique=True)),
                ('description', models.TextField(blank=True, null=True, verbose_name='توضیحات و نحوه اجرا')),
                ('primary_muscles', models.JSONField(default=list, help_text="لیست عضلات اصلی هدف (مثلاً ['quadriceps', 'gluteus_maximus'])")),
                ('secondary_muscles', models.JSONField(blank=True, default=list, help_text='لیست عضلات کمکی')),
                ('kinematic_chain', models.CharField(choices=[('open', 'Open Kinematic Chain (OKC)'), ('closed', 'Closed Kinematic Chain (CKC)')], default='closed', max_length=20)),
                ('plane_of_motion', models.CharField(choices=[('sagittal', 'Sagittal Plane'), ('frontal', 'Frontal Plane'), ('transverse', 'Transverse Plane'), ('multi_planar', 'Multi-Planar')], default='sagittal', max_length=20)),
                ('difficulty', models.CharField(choices=[('beginner', 'Beginner'), ('intermediate', 'Intermediate'), ('advanced', 'Advanced'), ('elite', 'Elite')], default='intermediate', max_length=20)),
                ('target_joints_to_analyze', models.JSONField(default=list, help_text="مفاصل بحرانی برای آنالیز هوش مصنوعی (مثلاً ['left_knee', 'right_knee', 'hip', 'lower_spine'])")),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'حرکت ورزشی',
                'verbose_name_plural': 'بانک حرکات ورزشی',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='CompletedSessionSummary',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('neo4j_session_uuid', models.UUIDField(help_text='آی\u200cدی تطبیق داده شده با Root Node در Neo4j', unique=True)),
                ('total_completed_reps', models.PositiveIntegerField(default=0)),
                ('valid_reps_count', models.PositiveIntegerField(default=0)),
                ('invalid_reps_count', models.PositiveIntegerField(default=0)),
                ('overall_form_score', models.FloatField(help_text='امتیاز فرم بیومکانیکی از ۱۰۰')),
                ('detected_compensations', models.JSONField(default=list, help_text="جبران\u200cهای حرکتی و خطاهای شناساگر (مثلاً ['knee_valgus', 'excessive_forward_lean'])")),
                ('joint_range_of_motion_summary', models.JSONField(default=dict, help_text="دامنه حرکتی ثبت شده برای مفاصل کلیدی (مثلاً {'knee_flexion_max': 118.5})")),
                ('perceived_rpe', models.FloatField(blank=True, help_text='فشار گزارش شده توسط ورزشکار', null=True)),
                ('ai_feedback_summary', models.TextField(blank=True, help_text='توصیه و تحلیل نهایی متنی سیستم هوش مصنوعی', null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='session_summaries', to=settings.AUTH_USER_MODEL)),
                ('exercise', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='session_summaries', to='workouts.exercise')),
            ],
            options={
                'verbose_name': 'خلاصه جلسه تمرینی',
                'verbose_name_plural': 'خلاصه\u200cهای جلسات تمرینی',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='WorkoutPlan',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=200, verbose_name='عنوان برنامه')),
                ('description', models.TextField(blank=True, null=True)),
                ('is_active', models.BooleanField(default=True, verbose_name='برنامه فعال')),
                ('start_date', models.DateField(auto_now_add=True)),
                ('end_date', models.DateField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='workout_plans', to=settings.AUTH_USER_MODEL, verbose_name='ورزشکار')),
            ],
            options={
                'verbose_name': 'برنامه تمرینی',
                'verbose_name_plural': 'برنامه\u200cهای تمرینی',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='WorkoutPlanItem',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('order', models.PositiveIntegerField(default=1, help_text='ترتیب اجرای حرکت در جلسه')),
                ('target_sets', models.PositiveIntegerField(default=3)),
                ('target_reps_scheme', models.JSONField(default=list, help_text='الگوی تکرار تجویز شده مثلا [10, 8, 6]')),
                ('prescribed_rpe', models.FloatField(blank=True, help_text='درجه فشار تجویز شده (RPE 1-10)', null=True)),
                ('tempo', models.CharField(default='3-1-1-0', help_text='اکسنتوریک-مکث-کنسنتریک-مکث', max_length=20)),
                ('rest_period_seconds', models.PositiveIntegerField(default=90)),
                ('notes', models.TextField(blank=True, null=True)),
                ('exercise', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='plan_items', to='workouts.exercise')),
                ('plan', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='workouts.workoutplan')),
            ],
            options={
                'verbose_name': 'حرکت در برنامه',
                'verbose_name_plural': 'حرکات برنامه\u200cهای تمرینی',
                'ordering': ['order'],
            },
        ),
    ]
