apiVersion: apps/v1
kind: Deployment
metadata:
  name: neo4j-gds-deployment
  labels:
    app: neo4j-gds
spec:
  replicas: 1
  strategy:
    type: Recreate  # 👈 اجبار به بستن پاد قدیمی قبل از ساخت پاد جدید (جلوگیری از کمبود منابع)
  selector:
    matchLabels:
      app: neo4j-gds
  template:
    metadata:
      labels:
        app: neo4j-gds
    spec:
      containers:
      - name: neo4j-gds
        image: neo4j:5.26.0-enterprise
        env:
        - name: NEO4J_AUTH
          value: "neo4j/password123"
        - name: NEO4J_PLUGINS
          value: '["graph-data-science"]'
        - name: NEO4J_ACCEPT_LICENSE_AGREEMENT
          value: "yes"
        - name: NEO4J_server_config_strict__validation_enabled
          value: "false"
        - name: NEO4J_cypher_default__language__version
          value: "CYPHER 2025"
        - name: NEO4J_internal_dbms_cypher__gql__support__enabled
          value: "true"
        ports:
        - containerPort: 7474
          name: http
        - containerPort: 7687
          name: bolt
        resources:
          requests:
            memory: "1Gi"  # 👈 سبک‌تر برای محیط لوکال
            cpu: "500m"
          limits:
            memory: "2Gi"
            cpu: "1500m"