services:
  dgl:
    build: .
    image: dgl_env_imprvd:latest
    container_name: dgl_container__imprvd
    volumes:
      - .:/workspace
    environment:
      - DGL_DISABLE_GRAPHBOLT=1
      - DGLBACKEND=pytorch
    stdin_open: true
    tty: true
    working_dir: /workspace