# Generated by Django 5.2.17 on 2026-09-08 01:48

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='BiomechanicalSession',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('exercise_type', models.CharField(max_length=100, verbose_name='نوع حرکت ورزشی')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('status', models.CharField(choices=[('pending', 'در انتظار پردازش'), ('processing', 'در حال پردازش خط لوله AI'), ('completed', 'تکمیل\u200cشده'), ('failed', 'خطا در پردازش')], default='pending', max_length=20)),
                ('notes', models.TextField(blank=True, null=True, verbose_name='توضیحات و ملاحظات')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sessions', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='FrameAnalysis',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('frame_number', models.PositiveIntegerField(verbose_name='شماره فریم')),
                ('keypoints_data', models.JSONField(verbose_name='مختصات کی\u200cپوینت\u200cها')),
                ('joint_angles', models.JSONField(blank=True, null=True, verbose_name='زوایای مفاصل')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='frames', to='users.biomechanicalsession')),
            ],
            options={
                'ordering': ['frame_number'],
            },
        ),
    ]
