# Generated by Django 5.2.17 on 2026-09-08 15:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_biomechanicalsession_frameanalysis'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userprofile',
            name='age',
        ),
        migrations.AddField(
            model_name='biomechanicalsession',
            name='rest_interval_seconds',
            field=models.PositiveIntegerField(default=60, verbose_name='زمان استراحت محاسبه\u200cشده بین ست\u200cها (ثانیه)'),
        ),
        migrations.AddField(
            model_name='biomechanicalsession',
            name='set_system',
            field=models.CharField(choices=[('straight', 'ست معمولی'), ('superset', 'سوپرست'), ('giant_set', 'جاینت ست (۴ تایی)'), ('pyramid', 'هرمی (مثلاً ۱۲-۱۰-۸)'), ('drop_set', 'دراپ ست')], default='straight', max_length=50, verbose_name='سیستم ساختار ست'),
        ),
        migrations.AddField(
            model_name='biomechanicalsession',
            name='target_reps_scheme',
            field=models.JSONField(blank=True, default=list, verbose_name='الگوی تکرار هدف در ست\u200cها (مثلاً [12, 10, 8] یا [15, 15, 15])'),
        ),
        migrations.AddField(
            model_name='biomechanicalsession',
            name='tempo',
            field=models.CharField(blank=True, default='2-0-2-0', max_length=20, verbose_name='ریتم اجرای حرکت (Tempo: Eccentric-Pause-Concentric-Pause)'),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='baseline_flexibility_limits',
            field=models.JSONField(blank=True, default=dict, verbose_name='محدودیت\u200cهای انعطاف\u200cپذیری و دامنه حرکتی مفاصل'),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='date_of_birth',
            field=models.DateField(blank=True, null=True, verbose_name='تاریخ تولد'),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='femur_length_cm',
            field=models.FloatField(blank=True, null=True, verbose_name='طول استخوان ران (سانتی\u200cمتر)'),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='gender',
            field=models.CharField(blank=True, choices=[('male', 'مرد'), ('female', 'زن'), ('other', 'سایر')], max_length=15, null=True, verbose_name='جنسیت بیولوژیک'),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='medical_conditions',
            field=models.JSONField(blank=True, default=list, verbose_name='بیماری\u200cهای زمینه\u200cای و مزمن'),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='occupational_lifestyle',
            field=models.CharField(choices=[('sedentary_desk', 'نشسته / پشت میزی'), ('active_standing', 'ایستاده / فعال'), ('heavy_labor', 'کار فیزیکی سنگین')], default='sedentary_desk', max_length=50, verbose_name='الگوی حرکتی و وضعیت شغلی روزمره'),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='physiological_status',
            field=models.CharField(choices=[('none', 'عادی / بدون شرایط خاص'), ('pregnant', 'باردار'), ('menstruating', 'دوره ماهانه / قاعدگی'), ('postpartum', 'پس از زایمان')], default='none', max_length=50, verbose_name='وضعیت فیزیولوژیک جاری'),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='postural_deviations',
            field=models.JSONField(blank=True, default=list, verbose_name='ناهنجاری\u200cهای قامتی (مانند زانوی ضربدری، پشت گرد، گودی کمر)'),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='preferred_training_style',
            field=models.CharField(choices=[('straight_sets', 'ست\u200cهای معمولی و استاندارد'), ('supersets', 'سوپرست (دو حرکت متوالی)'), ('giant_sets', 'جاینت ست / سوپرست ۴ تایی'), ('pyramid_sets', 'سیستم هرمی (کاهش تکرار / افزایش وزنه)'), ('reverse_pyramid', 'هرمی معکوس'), ('high_rep_endurance', 'تکرارهای بالا و استقامتی (۱۵+ تکرار)'), ('drop_sets', 'دراپ ست (کاهش وزنه بدون استراحت)')], default='straight_sets', max_length=50, verbose_name='ترجیح سبک و سیستم تمرینی'),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='primary_goal',
            field=models.CharField(choices=[('general_fitness', 'تناسب اندام عمومی'), ('fat_loss', 'کاهش وزن و چربی\u200cسوزی'), ('hypertrophy_general', 'عضله\u200cسازی عمومی'), ('hypertrophy_glutes', 'هایپرتروفی و فرم\u200cدهی تخصصی سرینی (کپل)'), ('explosive_power', 'توسعه توان و قدرت انفجاری'), ('max_strength', 'افزایش حداکثر قدرت (Powerlifting)'), ('physiotherapy_rehab', 'فیزیوتراپی و توانبخشی پس از آسیب/جراحی'), ('corrective_exercise', 'حرکات اصلاحی (اصلاح پاسچر و ناهنجاری قامتی)')], default='general_fitness', max_length=50, verbose_name='هدف اصلی از تمرین'),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='target_sport',
            field=models.CharField(default='general_fitness', max_length=100, verbose_name='رشته ورزشی تخصصی'),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='therapy_details',
            field=models.JSONField(blank=True, default=dict, verbose_name='دستورالعمل و محدودیت\u200cهای فیزیوتراپی/پزشکی'),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='tibia_length_cm',
            field=models.FloatField(blank=True, null=True, verbose_name='طول ساق پا (سانتی\u200cمتر)'),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='torso_length_cm',
            field=models.FloatField(blank=True, null=True, verbose_name='طول تنه (سانتی\u200cمتر)'),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='used_equipment_gear',
            field=models.JSONField(blank=True, default=list, verbose_name='تجهیزات تمرینی مورداستفاده (مانند کمربند، کفش وزنه برداری، زانوبند)'),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='fitness_level',
            field=models.CharField(choices=[('beginner', 'مبتدی / بیمار تحت درمان'), ('intermediate', 'متوسط'), ('advanced', 'پیشرفته')], default='beginner', max_length=50, verbose_name='سطح آمادگی جسمانی'),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='injury_history',
            field=models.JSONField(blank=True, default=list, verbose_name='سابقه آسیب\u200cدیدگی\u200cهای اسکلتی-عضلانی'),
        ),
    ]
